decks:
    type: rest
    prefix: /v1
    resource: "Shuffle\CardBundle\Controller\DeckController"
    name_prefix:  api_1_ # naming collision
cards:
    type: rest
    parent: decks
    resource: "Shuffle\CardBundle\Controller\CardController"
    name_prefix:  api_1_ # naming collision
